# Generated by Django 5.0.4 on 2024-06-03 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_orderdetails_userid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderDetails',
        ),
    ]
