# Generated by Django 5.0.4 on 2024-06-07 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0009_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
