# Generated by Django 5.0.4 on 2024-06-13 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0011_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetails',
            name='userId',
        ),
    ]
