# Generated by Django 5.0.4 on 2024-06-13 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0012_remove_orderdetails_userid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderDetails',
        ),
    ]
