# Generated by Django 5.0.4 on 2024-06-13 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0013_delete_orderdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('itemprice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('orderDate', models.DateTimeField(auto_now_add=True)),
                ('orderid', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='client.order')),
                ('toyid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.toy')),
            ],
        ),
    ]
