# Generated by Django 5.0.4 on 2024-06-19 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0017_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='orderId',
            field=models.BigIntegerField(default=None),
        ),
    ]
