# Generated by Django 5.0.4 on 2024-07-03 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0018_order_orderid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='orderId',
            field=models.BigIntegerField(default=1),
        ),
    ]
